### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException during FastEvaluator generation

### ISSUE THREAD

**Issue by tchaye59** [thomasmueller/minperf#12]
I tried to execute this code and I got java.lang.ArrayIndexOutOfBoundsException

`
   @org.junit.Test
    public void test() {
        
        Builder builder = new Builder();

        long[] ls = new long[]{10, 20, 50};

        BitBuffer bb = builder.generate(ls);
        FastEvaluator evaluator = builder.evaluator(bb);

        for (long l : ls) {
            System.out.println(l + " -> " + evaluator.evaluate(l));
        }

    }`
Is there an error in my code?

This is the full exception trace : 
`java.lang.ArrayIndexOutOfBoundsException: 1
	at org.minperf.BitBuffer.readBit(BitBuffer.java:130)
	at org.minperf.BitBuffer.readEliasDelta(BitBuffer.java:264)
	at org.minperf.hem.recsplit.FastEvaluator.<init>(FastEvaluator.java:19)
	at org.minperf.hem.recsplit.Builder.evaluator(Builder.java:34)
	at net.almightshell.experiments.Test.compareSpace(Test.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.execute(JUnit4TestSet.java:53)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:123)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:104)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)`

**Comment by tchaye59** [comment]
I don't know the problem with the previous code . But it work with this one .

`public void test() {
        
        List<Long> list = new ArrayList() ;
        list.add(4L);
        list.add(12L);
        list.add(84L);
        list.add(23L);
        list.add(4495L);
                
        RecSplitBuilder<Long> builder = RecSplitBuilder.newInstance(new LongHash());
        builder.leafSize(7);
        builder.averageBucketSize(1000);
        builder.maxChunkSize(1_000_000);
        
        BitBuffer buff = builder.generate(list);
        RecSplitEvaluator<Long> evaluator = builder.buildEvaluator(buff);
        
        for (Long l : list) {
            System.out.println(l+"->"+evaluator.evaluate(l));
        }
        
        
        
        System.out.println((double) buff.position() / list.size() + " bits/key");
        

    }`

It would have been very interesting for my research if the RecSplit algorithm kept the order of adding the elements during the evaluation  .
